# Project: xmltest
# Makefile created by Dev-C++ 5.4.2

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"C:/Program Files/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -L"C:/Documents and Settings/User/桌面/OK/tinyxml_content/lib" "../../../../../../Documents and Settings/User/桌面/OK/tinyxml_content/lib/libtinyxml.a" "../../../../../../Documents and Settings/User/桌面/OK/tinyxml_content/lib/libtinyxmlstl.a"  -m32 -g3
INCS     = -I"C:/Program Files/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Documents and Settings/User/桌面/OK/tinyxml_content/include"
CXXINCS  = -I"C:/Program Files/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Documents and Settings/User/桌面/OK/tinyxml_content/include"
BIN      = xmltest.exe
CXXFLAGS = $(CXXINCS) -m32 -g3
CFLAGS   = $(INCS) -m32 -g3
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
